<?php
/**
 * Title: HookAndSail - Default Header
 * Slug: hookandsail/header-default
 * Categories: blockstrap-site-header
 * Viewport Width: 1280
 */

 $logo_url = esc_url( get_theme_file_uri( 'assets/images/logo-no-background.png' ) ); /* <?php echo esc_url( $logo_url ); ?> */

?>

<!-- wp:blockstrap/blockstrap-widget-skip-links {"content":"\u003ca href=\u0022#main\u0022 class=\u0022btn btn-primary\u0022\u003eSkip to main content\u003c/a\u003e"} -->
[bs_skip_links text1='Skip to main content'  hash1='main'  text2=''  hash2=''  text3=''  hash3=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  css_class='' ]
<!-- /wp:blockstrap/blockstrap-widget-skip-links -->

<!-- wp:blockstrap/blockstrap-widget-navbar {"bg":"white","bg_color":"rgba(255,255,255,0.84)","inner_container":"container","mr":"0","mb_lg":"","pr":"0","pl":"3","pt_lg":"3","pr_lg":"3","pb_lg":"2","border":"0"} -->
[bs_navbar bg='white'  bg_color='rgba(255,255,255,0.84)'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bgtus='false'  cscos='false'  container=''  inner_container='container'  mt=''  mr='0'  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr='0'  pb=''  pl='3'  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='3'  pr_lg='3'  pb_lg='2'  pl_lg=''  border='0'  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom='' ]<nav class="navbar navbar-expand-lg me-0 pe-0 ps-3 pt-3 pe-lg-3 pb-2 border-0 bg-white"><div class="wp-block-blockstrap-blockstrap-widget-navbar container"><!-- wp:blockstrap/blockstrap-widget-navbar-brand {"text":"","icon_image":"<?php echo esc_url( $logo_url ); ?>","img_max_width":100,"custom_url":"/","brand_font_size":"h1","brand_font_weight":"font-weight-normal","brand_font_italic":"font-italic","bg_gradient":"linear-gradient(135deg,rgb(34,227,7) 0%,rgb(245,245,245) 100%)","bg_on_text":true,"mb_lg":"","rounded_size":"lg"} -->
[bs_navbar_brand text=''  icon_image='<?php echo esc_url( $logo_url ); ?>'  img_max_width='100'  type='home'  custom_url='/'  text_color=''  brand_font_size='h1'  brand_font_weight='font-weight-normal'  brand_font_italic='font-italic'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgb(34,227,7) 0%,rgb(245,245,245) 100%)'  bg_on_text='true'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size='lg'  shadow=''  css_class='' ]<a class="navbar-brand d-flex align-items-center rounded-lg" href="http://hookandsail.local"><img class="" alt="Site logo" src="<?php echo esc_url( $logo_url ); ?>" style="max-width:100px" width="100" height="50"/><span class="mb-0 props.attributes.brand_font_size props.attributes.brand_font_weight fst-italic"></span></a>[/bs_navbar_brand]
<!-- /wp:blockstrap/blockstrap-widget-navbar-brand -->

<!-- wp:blockstrap/blockstrap-widget-nav {"anchor":"main-nav","inside_navbar":"1","font_size":"fs-base","ml_lg":"","rounded_size":"lg","width":"w-100"} -->
[bs_nav anchor='main-nav'  inside_navbar='1'  container=''  flex_direction=''  nav_style=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  nav_fill=''  font_size='fs-base'  font_size_custom=''  bg=''  mt=''  mr='auto'  mb=''  ml='auto'  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg='0'  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size='lg'  shadow=''  width='w-100'  css_class='' ]<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav_main-nav" aria-label="Open menu"><span class="navbar-toggler-icon"></span></button><div class="wp-block-blockstrap-blockstrap-widget-nav blockstrap-nav collapse navbar-collapse" id="navbarNav_main-nav"><ul class="wp-block-blockstrap-blockstrap-widget-nav navbar-nav me-auto ms-auto me-lg-0 rounded-lg w-100 fs-base"><!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"gd_place","page_id":"1858","custom_url":"#about","text":"Stays","text_color":"dark","ml":"0","ml_lg":"auto","content":"\u003ca href=\u0022#http://hookandsail.local/place/\u0022 class=\u0022nav-link link-dark \u0022 \u003eStays\u003c/a\u003e"} -->
[bs_nav_item type='gd_place'  page_id='1858'  post_id=''  custom_url='#about'  text='Stays'  icon_class=''  icon_aria_label=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='dark'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight=''  mt=''  mr=''  mb=''  ml='0'  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg='auto'  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]
<!-- /wp:blockstrap/blockstrap-widget-nav-item -->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"gd_location","custom_url":"#","text":"Destinations","text_color":"dark","content":"\u003ca href=\u0022#http://hookandsail.local/location/\u0022 class=\u0022nav-link link-dark \u0022 \u003eDestinations\u003c/a\u003e"} -->
[bs_nav_item type='gd_location'  page_id=''  post_id=''  custom_url='#'  text='Destinations'  icon_class=''  icon_aria_label=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='dark'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]
<!-- /wp:blockstrap/blockstrap-widget-nav-item -->

<!-- wp:blockstrap/blockstrap-widget-nav-dropdown {"text":"Account","icon_class":"fa-regular fa-user","link_type":"btn","link_size":"large","link_bg":"outline-primary","ml":"0","ml_lg":"2","border":"0"} -->
[bs_nav_dropdown text='Account'  icon_class='fa-regular fa-user'  link_type='btn'  link_size='large'  link_bg='outline-primary'  link_divider=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml='0'  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg='2'  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border='0'  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]<li class="wp-block-blockstrap-blockstrap-widget-nav-dropdown nav-item dropdown form-inline ms-0 ms-lg-2 border-0"><a class="dropdown-toggle nav-link btn btn-outline-primary btn-lg text-" href="#" roll="button" data-toggle="dropdown" aria-expanded="false"><i class="fa-regular fa-user mr-2 me-2"></i>Account</a><ul class="wp-block-blockstrap-blockstrap-widget-nav-dropdown dropdown-menu"><!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"page","page_id":"5238","text":"Dashboard","icon_class":"fa-solid fa-gauge","visibility_conditions":"{\u0022rule1\u0022:{\u0022type\u0022:\u0022logged_out\u0022},\u0022output\u0022:{\u0022type\u0022:\u0022hide\u0022}}","content":"\u003ca href=\u0022#http://hookandsail.local/account/\u0022 class=\u0022dropdown-item \u0022 \u003e\u003ci class=\u0022fa-solid fa-gauge me-2\u0022\u003e\u003c/i\u003eDashboard\u003c/a\u003e"} -->
[bs_nav_item type='page'  page_id='5238'  post_id=''  custom_url=''  text='Dashboard'  icon_class='fa-solid fa-gauge'  icon_aria_label=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions='{"rule1":{"type":"logged_out"},"output":{"type":"hide"}}'  css_class='' ]
<!-- /wp:blockstrap/blockstrap-widget-nav-item -->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"page","page_id":"5242","text":"Profile","icon_class":"fa-regular fa-id-badge","visibility_conditions":"{\u0022rule1\u0022:{\u0022type\u0022:\u0022logged_out\u0022},\u0022output\u0022:{\u0022type\u0022:\u0022hide\u0022}}","content":"\u003ca href=\u0022#http://hookandsail.local/profile/\u0022 class=\u0022dropdown-item \u0022 \u003e\u003ci class=\u0022fa-regular fa-id-badge me-2\u0022\u003e\u003c/i\u003eProfile\u003c/a\u003e"} -->
[bs_nav_item type='page'  page_id='5242'  post_id=''  custom_url=''  text='Profile'  icon_class='fa-regular fa-id-badge'  icon_aria_label=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions='{"rule1":{"type":"logged_out"},"output":{"type":"hide"}}'  css_class='' ]
<!-- /wp:blockstrap/blockstrap-widget-nav-item -->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"page","page_id":"5237","text":"Login","visibility_conditions":"{\u0022rule1\u0022:{\u0022type\u0022:\u0022logged_in\u0022},\u0022output\u0022:{\u0022type\u0022:\u0022hide\u0022}}","content":"\u003ca href=\u0022#http://hookandsail.local/login/\u0022 class=\u0022dropdown-item \u0022 \u003eLogin\u003c/a\u003e"} -->
[bs_nav_item type='page'  page_id='5237'  post_id=''  custom_url=''  text='Login'  icon_class=''  icon_aria_label=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions='{"rule1":{"type":"logged_in"},"output":{"type":"hide"}}'  css_class='' ]
<!-- /wp:blockstrap/blockstrap-widget-nav-item -->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"page","page_id":"5236","text":"Register","visibility_conditions":"{\u0022rule1\u0022:{\u0022type\u0022:\u0022logged_in\u0022},\u0022output\u0022:{\u0022type\u0022:\u0022hide\u0022}}","content":"\u003ca href=\u0022#http://hookandsail.local/register/\u0022 class=\u0022dropdown-item \u0022 \u003eRegister\u003c/a\u003e"} -->
[bs_nav_item type='page'  page_id='5236'  post_id=''  custom_url=''  text='Register'  icon_class=''  icon_aria_label=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions='{"rule1":{"type":"logged_in"},"output":{"type":"hide"}}'  css_class='' ]
<!-- /wp:blockstrap/blockstrap-widget-nav-item -->

<!-- wp:separator {"backgroundColor":"gray","className":"is-style-wide"} -->
<hr class="wp-block-separator has-text-color has-gray-color has-alpha-channel-opacity has-gray-background-color has-background is-style-wide"/>
<!-- /wp:separator -->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"page","page_id":"4426","text":"List your property","icon_class":"fa-solid fa-plus","pt_lg":"2","content":"\u003ca href=\u0022#http://hookandsail.local/add-listing/\u0022 class=\u0022dropdown-item \u0022 \u003e\u003ci class=\u0022fa-solid fa-plus me-2\u0022\u003e\u003c/i\u003eList your property\u003c/a\u003e"} -->
[bs_nav_item type='page'  page_id='4426'  post_id=''  custom_url=''  text='List your property'  icon_class='fa-solid fa-plus'  icon_aria_label=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='2'  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]
<!-- /wp:blockstrap/blockstrap-widget-nav-item --></ul></li>[/bs_nav_dropdown]
<!-- /wp:blockstrap/blockstrap-widget-nav-dropdown --></ul></div>[/bs_nav]
<!-- /wp:blockstrap/blockstrap-widget-nav --></div></nav>[/bs_navbar]
<!-- /wp:blockstrap/blockstrap-widget-navbar -->