<?php
/**
 * Title: HookAndSail - Default Header
 * Slug: hookandsail/header-default
 * Categories: blockstrap-site-header
 * Viewport Width: 1280
 */

  $logo_url = esc_url( get_theme_file_uri( 'assets/images/logo-white.svg' ) ); /* <?php echo esc_url( $logo_url ); ?> */

?>

<!-- wp:blockstrap/blockstrap-widget-skip-links {"content":"\u003ca href=\u0022#main\u0022 class=\u0022btn btn-primary\u0022\u003eSkip to main content\u003c/a\u003e","sd_shortcode":"[bs_skip_links text1='Skip to main content'  hash1='main'  text2=''  hash2=''  text3=''  hash3=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  css_class='' ]"} /-->

<!-- wp:blockstrap/blockstrap-widget-navbar {"bg":"gray-dark","bg_color":"rgba(255,255,255,0.84)","bgtus":true,"container":"navbar-dark","inner_container":"container","mb_lg":"","pt_lg":"4","pb_lg":"4","border":"0","position":"fixed-top","content":"\u003ca href=\u0022#main\u0022 class=\u0022btn btn-primary\u0022\u003eSkip to main content\u003c/a\u003e","sd_shortcode":"[bs_navbar bg='gray-dark'  bg_color='rgba(255,255,255,0.84)'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bgtus='true'  cscos='false'  container='navbar-dark'  inner_container='container'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='4'  pr_lg=''  pb_lg='4'  pl_lg=''  border='0'  rounded=''  rounded_size=''  shadow=''  position='fixed-top'  sticky_offset_top=''  sticky_offset_bottom='' ]","sd_shortcode_close":"[/bs_navbar]"} -->
<nav class="navbar navbar-expand-lg pt-4 pb-4 border-0 bg-gray-dark bg-image-fixed bg-transparent-until-scroll navbar-dark fixed-top"><div class="wp-block-blockstrap-blockstrap-widget-navbar container"><!-- wp:blockstrap/blockstrap-widget-navbar-brand {"text":"","icon_image":"<?php echo esc_url( $logo_url ); ?>","img_max_width":200,"custom_url":"/","brand_font_size":"h1","brand_font_weight":"font-weight-normal","brand_font_italic":"font-italic","bg_gradient":"linear-gradient(135deg,rgb(34,227,7) 0%,rgb(245,245,245) 100%)","bg_on_text":true,"mb_lg":"","rounded_size":"lg","sd_shortcode":"[bs_navbar_brand text=''  icon_image='<?php echo esc_url( $logo_url ); ?>'  img_max_width='200'  type='home'  custom_url='/'  text_color=''  brand_font_size='h1'  brand_font_weight='font-weight-normal'  brand_font_italic='font-italic'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgb(34,227,7) 0%,rgb(245,245,245) 100%)'  bg_on_text='true'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size='lg'  shadow=''  css_class='' ]"} -->
<a class="navbar-brand d-flex align-items-center rounded-lg" href="https://hookandsail.local"><img class="" alt="Site logo" src="<?php echo esc_url( $logo_url ); ?>" style="max-width:200px" width="200" height="50"/><span class="mb-0 props.attributes.brand_font_size props.attributes.brand_font_weight fst-italic"></span></a>
<!-- /wp:blockstrap/blockstrap-widget-navbar-brand -->

<!-- wp:blockstrap/blockstrap-widget-nav {"anchor":"main-nav","font_size":"fs-5","mr_lg":"","ml_lg":"","rounded_size":"lg","width":"w-100","sd_shortcode":"[bs_nav anchor='main-nav'  inside_navbar='1'  container=''  flex_direction=''  nav_style=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  nav_fill=''  font_size='fs-5'  font_size_custom=''  bg=''  mt=''  mr='auto'  mb=''  ml='auto'  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size='lg'  shadow=''  width='w-100'  css_class='' ]","sd_shortcode_close":"[/bs_nav]"} -->
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav_main-nav" aria-label="Open menu"><span class="navbar-toggler-icon"></span></button><div class="wp-block-blockstrap-blockstrap-widget-nav blockstrap-nav collapse navbar-collapse" id="navbarNav_main-nav"><ul class="wp-block-blockstrap-blockstrap-widget-nav navbar-nav me-auto ms-auto rounded-lg w-100 fs-5"><!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"gd_place","page_id":"1858","custom_url":"#about","text":"Explore","text_color":"white","ml":"0","ml_lg":"auto","content":"\u003ca href=\u0022#https://hookandsail.local/place/\u0022 class=\u0022nav-link link-white \u0022 \u003eExplore\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='gd_place'  page_id='1858'  post_id=''  taxonomy=''  term_id=''  custom_url='#about'  text='Explore'  icon_class=''  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight=''  mt=''  mr=''  mb=''  ml='0'  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg='auto'  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]"} /-->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"gd_location","custom_url":"#","text":"Locations","text_color":"white","content":"\u003ca href=\u0022#https://hookandsail.local/location/\u0022 class=\u0022nav-link link-white \u0022 \u003eLocations\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='gd_location'  page_id=''  post_id=''  taxonomy=''  term_id=''  custom_url='#'  text='Locations'  icon_class=''  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]"} /-->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"page","page_id":"3336","custom_url":"#","text":"Learn","text_color":"white","content":"\u003ca href=\u0022#https://hookandsail.local/blog/\u0022 class=\u0022nav-link link-white \u0022 \u003eLearn\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='page'  page_id='3336'  post_id=''  taxonomy=''  term_id=''  custom_url='#'  text='Learn'  icon_class=''  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]"} /-->

<!-- wp:blockstrap/blockstrap-widget-nav-dropdown {"icon_class":"fa-regular fa-user","link_type":"btn","link_size":"large","link_bg":"primary","dropdown_hide_pointer":true,"text_color":"white","ml":"0","ml_lg":"2","pr":"0","pl":"0","border":"0","sd_shortcode":"[bs_nav_dropdown text=''  icon_class='fa-regular fa-user'  link_type='btn'  link_size='large'  link_bg='primary'  link_divider=''  dropdown_hide_pointer='true'  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml='0'  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg='2'  pt=''  pr='0'  pb=''  pl='0'  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border='0'  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]","sd_shortcode_close":"[/bs_nav_dropdown]"} -->
<li class="wp-block-blockstrap-blockstrap-widget-nav-dropdown nav-item dropdown form-inline ms-0 ms-lg-2 pe-0 ps-0 border-0 text-white"><a class="dropdown-toggle nav-link btn btn-primary btn-lg text-white" href="#" roll="button" data-toggle="dropdown" aria-expanded="false"><i class="fa-regular fa-user"></i></a><ul class="wp-block-blockstrap-blockstrap-widget-nav-dropdown dropdown-menu dropdown-caret-0"><!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"page","page_id":"5238","text":"Dashboard","visibility_conditions":"{\u0022rule1\u0022:{\u0022type\u0022:\u0022logged_out\u0022},\u0022output\u0022:{\u0022type\u0022:\u0022hide\u0022}}","content":"\u003ca href=\u0022#https://hookandsail.local/account/\u0022 class=\u0022dropdown-item \u0022 \u003eDashboard\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='page'  page_id='5238'  post_id=''  taxonomy=''  term_id=''  custom_url=''  text='Dashboard'  icon_class=''  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions='{\u0022rule1\u0022:{\u0022type\u0022:\u0022logged_out\u0022},\u0022output\u0022:{\u0022type\u0022:\u0022hide\u0022}}'  css_class='' ]"} /-->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"page","page_id":"5242","text":"Profile","visibility_conditions":"{\u0022rule1\u0022:{\u0022type\u0022:\u0022logged_out\u0022},\u0022output\u0022:{\u0022type\u0022:\u0022hide\u0022}}","content":"\u003ca href=\u0022#https://hookandsail.local/profile/\u0022 class=\u0022dropdown-item \u0022 \u003eProfile\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='page'  page_id='5242'  post_id=''  taxonomy=''  term_id=''  custom_url=''  text='Profile'  icon_class=''  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions='{\u0022rule1\u0022:{\u0022type\u0022:\u0022logged_out\u0022},\u0022output\u0022:{\u0022type\u0022:\u0022hide\u0022}}'  css_class='' ]"} /-->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"page","page_id":"5237","text":"Login","visibility_conditions":"{\u0022rule1\u0022:{\u0022type\u0022:\u0022logged_in\u0022},\u0022output\u0022:{\u0022type\u0022:\u0022hide\u0022}}","content":"\u003ca href=\u0022#https://hookandsail.local/login/\u0022 class=\u0022dropdown-item \u0022 \u003eLogin\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='page'  page_id='5237'  post_id=''  taxonomy=''  term_id=''  custom_url=''  text='Login'  icon_class=''  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions='{\u0022rule1\u0022:{\u0022type\u0022:\u0022logged_in\u0022},\u0022output\u0022:{\u0022type\u0022:\u0022hide\u0022}}'  css_class='' ]"} /-->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"page","page_id":"5236","text":"Register","visibility_conditions":"{\u0022rule1\u0022:{\u0022type\u0022:\u0022logged_in\u0022},\u0022output\u0022:{\u0022type\u0022:\u0022hide\u0022}}","content":"\u003ca href=\u0022#https://hookandsail.local/register/\u0022 class=\u0022dropdown-item \u0022 \u003eRegister\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='page'  page_id='5236'  post_id=''  taxonomy=''  term_id=''  custom_url=''  text='Register'  icon_class=''  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions='{\u0022rule1\u0022:{\u0022type\u0022:\u0022logged_in\u0022},\u0022output\u0022:{\u0022type\u0022:\u0022hide\u0022}}'  css_class='' ]"} /-->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"page","page_id":"4426","text":"Add Listing","content":"\u003ca href=\u0022#https://hookandsail.local/add-listing/\u0022 class=\u0022dropdown-item \u0022 \u003eAdd Listing\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='page'  page_id='4426'  post_id=''  taxonomy=''  term_id=''  custom_url=''  text='Add Listing'  icon_class=''  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]"} /--></ul></li>
<!-- /wp:blockstrap/blockstrap-widget-nav-dropdown --></ul></div>
<!-- /wp:blockstrap/blockstrap-widget-nav --></div></nav>
<!-- /wp:blockstrap/blockstrap-widget-navbar -->