<?php
/**
 * Title: HookAndSail - Default Hero Page
 * Slug: hookandsail/hero-page-default
 * Categories: blockstrap-hero-sections
 * Viewport Width: 1280
 */

$img_url = esc_url( get_theme_file_uri( 'assets/images/demo/lake.jpg' ) ); /* <?php echo esc_url( $img_url ); ?> */

?>

<!-- wp:blockstrap/blockstrap-widget-container {"container":"container-fluid","mb_lg":"5","pr_lg":"0","pl_lg":"0"} -->
[bs_container container='container-fluid'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='5'  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg='0'  pb_lg=''  pl_lg='0'  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-5 pe-0 ps-0 container-fluid"><!-- wp:blockstrap/blockstrap-widget-container {"container":"container-fluid","bg":"custom-gradient","bg_color":"#00000000","bg_gradient":"linear-gradient(180deg,rgba(0,0,0,0) 17%,rgba(0,0,0,0.72) 88%)","bg_image":"<?php echo esc_url( $img_url ); ?>","bg_image_id":5257,"bg_image_xy":{"x":0.51,"y":0.71},"mb_lg":"","pt":"7","pt_lg":"12","pr_lg":"0","pb_lg":"4","pl_lg":"0","position":"position-relative","display_lg":"d-lg-flex","flex_align_items_lg":"align-items-lg-end","flex_justify_content_lg":"justify-content-lg-center","overflow":"overflow-hidden"} -->
[bs_container container='container-fluid'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg='custom-gradient'  bg_color='#00000000'  bg_gradient='linear-gradient(180deg,rgba(0,0,0,0) 17%,rgba(0,0,0,0.72) 88%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image='<?php echo esc_url( $img_url ); ?>'  bg_image_id='5257'  bg_image_xy='{x:0.51,y:0.71}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt='7'  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='12'  pr_lg='0'  pb_lg='4'  pl_lg='0'  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position='position-relative'  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg='d-lg-flex'  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg='align-items-lg-end'  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg='justify-content-lg-center'  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow='overflow-hidden'  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined pt-7 pt-lg-12 pe-0 pb-4 ps-0 bg-custom-gradient d-flex container-fluid position-relative align-items-end justify-content-center overflow-hidden" style="background-image:linear-gradient(180deg,rgba(0,0,0,0) 17%,rgba(0,0,0,0.72) 88%),url(<?php echo esc_url( $img_url ); ?>);background-size:cover;background-position:51% 71%"><!-- wp:blockstrap/blockstrap-widget-shape-divider {"sd":"mountains","sd_position":"top","sd_color":"white","sd_width":"135","sd_height":"83","styleid":"block-2ez2qjgtm6g"} -->
[bs_shape_divider sd='mountains'  sd_position='top'  sd_color='white'  sd_custom_color='#0073aa'  sd_width='135'  sd_height='83'  sd_flip='false'  sd_invert='false'  sd_btf='false'  styleid='block-2ez2qjgtm6g' ]<div class="wp-block-blockstrap-blockstrap-widget-shape-divider block-2ez2qjgtm6g blockstrap-shape blockstrap-shape-top position-absolute"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 100" preserveAspectRatio="none">	<path class="bg-white blockstrap-shape-fill" opacity="0.33" d="M473,67.3c-203.9,88.3-263.1-34-320.3,0C66,119.1,0,59.7,0,59.7V0h1000v59.7 c0,0-62.1,26.1-94.9,29.3c-32.8,3.3-62.8-12.3-75.8-22.1C806,49.6,745.3,8.7,694.9,4.7S492.4,59,473,67.3z"/>	<path class="bg-white blockstrap-shape-fill" opacity="0.66" d="M734,67.3c-45.5,0-77.2-23.2-129.1-39.1c-28.6-8.7-150.3-10.1-254,39.1 s-91.7-34.4-149.2,0C115.7,118.3,0,39.8,0,39.8V0h1000v36.5c0,0-28.2-18.5-92.1-18.5C810.2,18.1,775.7,67.3,734,67.3z"/>	<path class="bg-white blockstrap-shape-fill" d="M766.1,28.9c-200-57.5-266,65.5-395.1,19.5C242,1.8,242,5.4,184.8,20.6C128,35.8,132.3,44.9,89.9,52.5C28.6,63.7,0,0,0,0 h1000c0,0-9.9,40.9-83.6,48.1S829.6,47,766.1,28.9z"/></svg></div><style>.block-2ez2qjgtm6g { pointer-events: none;background-repeat: no-repeat;left: -1px;right: -1px;top: -1px;line-height: 0;overflow: hidden;margin: 0 1px;}.block-2ez2qjgtm6g svg{ height: 83px;width: calc(135% + 1.3px);left: 50%;position: relative;display: block;-webkit-transform: translateX(-50%); -ms-transform: translateX(-50%); transform: translateX(-50%);}.block-2ez2qjgtm6g svg path{ }</style>[/bs_shape_divider]
<!-- /wp:blockstrap/blockstrap-widget-shape-divider -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"col","col":"12","col_lg":"7","mr_lg":"auto","ml_lg":"auto"} -->
[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col='12'  col_md=''  col_lg='7'  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg='auto'  mb_lg='3'  ml_lg='auto'  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined me-auto mb-3 ms-auto col-12 col-lg-7 col"><!-- wp:blockstrap/blockstrap-widget-post-title {"text_color":"white","font_weight":"font-weight-bold","text_align_lg":"text-lg-center"} -->
[bs_post_title html_tag='h1'  is_link='false'  stretched_link='false'  text_color='white'  text_color_custom=''  font_size=''  font_size_custom=''  font_line_height=''  font_weight='font-weight-bold'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg='text-lg-center'  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_on_text='false'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='3'  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  css_class='' ]
<!-- /wp:blockstrap/blockstrap-widget-post-title --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container -->