<?php
/**
 * Title: HookAndSail - Three-column testimonials block with a background image.
 * Slug: hookandsail/testimonials
 * Categories: blockstrap-page-content
 * Viewport Width: 1280
 */

$img_url = esc_url( get_theme_file_uri( 'assets/images/demo/montain-cabins.jpg' ) ); /* <?php echo esc_url( $img_url ); ?> */
$testimonial3 = esc_url( get_theme_file_uri( 'assets/images/demo/testimonial-3.png' ) ); /* <?php echo esc_url( $testimonial3 ); ?> */
$testimonial4 = esc_url( get_theme_file_uri( 'assets/images/demo/testimonial-4.png' ) ); /* <?php echo esc_url( $testimonial4 ); ?> */
$testimonial5 = esc_url( get_theme_file_uri( 'assets/images/demo/testimonial-5.png' ) ); /* <?php echo esc_url( $testimonial5 ); ?> */

?>

<!-- wp:blockstrap/blockstrap-widget-container {"container":"container-fluid","bg":"custom-color","bg_color":"rgba(0,0,0,0.7)","bg_image":"<?php echo esc_url( $img_url ); ?>","bg_image_id":5267,"bg_image_xy":{"x":0.52,"y":0.75},"mb_lg":"","pt":"5","pb":"5","pt_lg":"7","pb_lg":"10","position":"position-relative"} -->
[bs_container container='container-fluid'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg='custom-color'  bg_color='rgba(0,0,0,0.7)'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image='<?php echo esc_url( $img_url ); ?>'  bg_image_id='5267'  bg_image_xy='{x:0.52,y:0.75}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt='5'  pr=''  pb='5'  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='7'  pr_lg=''  pb_lg='10'  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position='position-relative'  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined pt-5 pb-5 pt-lg-7 pb-lg-10 bg-custom-color container-fluid position-relative" style="background-color:rgba(0,0,0,0.7);background-image:url(<?php echo esc_url( $img_url ); ?>);background-blend-mode:overlay;background-size:cover;background-position:52% 75%"><!-- wp:blockstrap/blockstrap-widget-container {"bg_color":"rgba(0,0,0,0.03)","mb_lg":""} -->
[bs_container container='container'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='rgba(0,0,0,0.03)'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined container"><!-- wp:blockstrap/blockstrap-widget-container {"container":"row","mb_lg":"5"} -->
[bs_container container='row'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='5'  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-5 row"><!-- wp:blockstrap/blockstrap-widget-container {"container":"col","mb_md":"4","mb_lg":"","display_lg":"d-lg-flex","flex_align_items_lg":"align-items-lg-center"} -->
[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md='4'  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg='d-lg-flex'  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg='align-items-lg-center'  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-md-4 d-flex col align-items-center"><!-- wp:blockstrap/blockstrap-widget-container {"container":"col","col_md":"8","col_lg":"6","text_color":"white","text_align_lg":"text-lg-start","mb_lg":""} -->
[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md='8'  col_lg='6'  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg='text-lg-start'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined col-md-8 col-lg-6 text-white text-start col"><!-- wp:blockstrap/blockstrap-widget-heading {"text":"Within each stay, a story unfolds.","html_tag":"h2","text_color":"black","font_size":"h1","font_weight":"font-weight-bold","text_align_lg":"text-lg-start","mr_lg":"3","mb_lg":""} -->
<h2 class="wp-block-blockstrap-blockstrap-widget-heading me-3 text-black text-start font-weight-bold h1">Within each stay, a story unfolds.</h2>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"The magic of HookAndSail? It's in the stories created within our walls. But to understand, you have to be a part of one.","html_tag":"div","text_color":"gray","font_size":"fs-6","font_weight":"font-weight-normal","text_align_lg":"text-lg-start","mr_lg":"3","mb_lg":""} -->
<div class="wp-block-blockstrap-blockstrap-widget-heading me-3 text-gray text-start font-weight-normal fs-6">The magic of HookAndSail? It's in the stories created within our walls. But to understand, you have to be a part of one.</div>
<!-- /wp:blockstrap/blockstrap-widget-heading --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"row","row_cols":"1","row_cols_md":"2","row_cols_lg":"3","mb_lg":""} -->
[bs_container container='row'  h100=''  row_cols='1'  row_cols_md='2'  row_cols_lg='3'  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined row-cols-1 row-cols-md-2 row-cols-lg-3 row"><!-- wp:blockstrap/blockstrap-widget-container {"container":"col","col_lg":"auto","mb_lg":"5"} -->
[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg='auto'  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='5'  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-5 col-auto col"><!-- wp:blockstrap/blockstrap-widget-container {"container":"","text_align_lg":"text-lg-center","mb_lg":"","pr_lg":"3","pl_lg":"3","border":"0","rounded":"rounded","rounded_size":"4","display_lg":"d-lg-block"} -->
[bs_container container=''  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg='text-lg-center'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg='3'  pb_lg=''  pl_lg='3'  border='0'  border_type=''  border_width=''  border_opacity=''  rounded='rounded'  rounded_size='4'  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg='d-lg-block'  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined pe-3 ps-3 border-0 rounded-4 text-center d-block rounded"><!-- wp:image {"width":"100px","height":"100px","scale":"cover","sizeSlug":"large","linkDestination":"none","align":"left","style":{"border":{"radius":"20px"}}} -->
<figure class="wp-block-image alignleft size-large is-resized has-custom-border"><img src="<?php echo esc_url( $testimonial3 ); ?>" alt="" style="border-radius:20px;object-fit:cover;width:100px;height:100px"/></figure>
<!-- /wp:image -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"\u0022We booked a last-minute HookAndSail. The city view was stunning, and the little welcome note with chocolates made it extra special. It's the perfect place to create lasting memories.\u0022","html_tag":"p","text_color":"white","font_size":"fs-6","font_line_height":1.7,"font_weight":"font-weight-normal","text_align_lg":"text-lg-start","mb_lg":"2"} -->
<p class="wp-block-blockstrap-blockstrap-widget-heading mb-2 text-white text-start font-weight-normal fs-6" style="line-height:1.7">"We booked a last-minute HookAndSail. The city view was stunning, and the little welcome note with chocolates made it extra special. It's the perfect place to create lasting memories."</p>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"David","html_tag":"h6","text_color":"white","font_size":"h4","font_weight":"font-weight-bold","text_align_lg":"text-lg-start","mt_lg":"3","mb_lg":"0"} -->
<h6 class="wp-block-blockstrap-blockstrap-widget-heading mt-3 mb-0 text-white text-start font-weight-bold h4">David</h6>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"New York","html_tag":"p","text_color":"white","font_size":"fs-base","font_weight":"font-weight-normal","text_align_lg":"text-lg-start","mb_lg":"0"} -->
<p class="wp-block-blockstrap-blockstrap-widget-heading mb-0 text-white text-start font-weight-normal fs-base">New York</p>
<!-- /wp:blockstrap/blockstrap-widget-heading --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"col","col_lg":"auto","mb_lg":"5"} -->
[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg='auto'  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='5'  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-5 col-auto col"><!-- wp:blockstrap/blockstrap-widget-container {"container":"","text_align_lg":"text-lg-center","mb_lg":"","pr_lg":"3","pl_lg":"3","border":"0","rounded":"rounded","rounded_size":"4","display_lg":"d-lg-block"} -->
[bs_container container=''  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg='text-lg-center'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg='3'  pb_lg=''  pl_lg='3'  border='0'  border_type=''  border_width=''  border_opacity=''  rounded='rounded'  rounded_size='4'  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg='d-lg-block'  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined pe-3 ps-3 border-0 rounded-4 text-center d-block rounded"><!-- wp:image {"width":"100px","height":"100px","scale":"cover","sizeSlug":"large","linkDestination":"none","align":"center","style":{"border":{"radius":"20px"}},"className":"is-style-rounded"} -->
<figure class="wp-block-image aligncenter size-large is-resized has-custom-border is-style-rounded"><img src="<?php echo esc_url( $testimonial4 ); ?>" alt="" style="border-radius:20px;object-fit:cover;width:100px;height:100px"/></figure>
<!-- /wp:image -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"\u0022Traveling solo can be impersonal, but HookAndSail's cozy space made me feel relaxed. I even met some fellow travelers by the pool – a story I wouldn't have had at a hotel.\u0022","html_tag":"p","text_color":"white","font_size":"fs-6","font_line_height":1.7,"font_weight":"font-weight-normal","text_align_lg":"text-lg-start","mb_lg":"2"} -->
<p class="wp-block-blockstrap-blockstrap-widget-heading mb-2 text-white text-start font-weight-normal fs-6" style="line-height:1.7">"Traveling solo can be impersonal, but HookAndSail's cozy space made me feel relaxed. I even met some fellow travelers by the pool – a story I wouldn't have had at a hotel."</p>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"James","html_tag":"h6","text_color":"white","font_size":"h4","font_weight":"font-weight-bold","text_align_lg":"text-lg-start","mt_lg":"3","mb_lg":"0"} -->
<h6 class="wp-block-blockstrap-blockstrap-widget-heading mt-3 mb-0 text-white text-start font-weight-bold h4">James</h6>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"Los Angeles","html_tag":"p","text_color":"white","font_size":"fs-base","font_weight":"font-weight-normal","text_align_lg":"text-lg-start","mb_lg":"0"} -->
<p class="wp-block-blockstrap-blockstrap-widget-heading mb-0 text-white text-start font-weight-normal fs-base">Los Angeles</p>
<!-- /wp:blockstrap/blockstrap-widget-heading --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"col","col_lg":"auto","mb_lg":"5"} -->
[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg='auto'  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='5'  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-5 col-auto col"><!-- wp:blockstrap/blockstrap-widget-container {"container":"","text_align_lg":"text-lg-center","mb_lg":"","pr_lg":"3","pl_lg":"3","border":"0","rounded":"rounded","rounded_size":"4","display_lg":"d-lg-block"} -->
[bs_container container=''  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg='text-lg-center'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg='3'  pb_lg=''  pl_lg='3'  border='0'  border_type=''  border_width=''  border_opacity=''  rounded='rounded'  rounded_size='4'  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg='d-lg-block'  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined pe-3 ps-3 border-0 rounded-4 text-center d-block rounded"><!-- wp:image {"width":"100px","height":"100px","scale":"cover","sizeSlug":"large","linkDestination":"none","align":"left","style":{"border":{"radius":"20px"}}} -->
<figure class="wp-block-image alignleft size-large is-resized has-custom-border"><img src="<?php echo esc_url( $testimonial5 ); ?>" alt="" style="border-radius:20px;object-fit:cover;width:100px;height:100px"/></figure>
<!-- /wp:image -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"\u0022Deadlines met, views enjoyed, HookAndSail's strong Wi-Fi and stylish workspace made remote work a breeze. Now that's a business trip I won't forget!\u0022","html_tag":"p","text_color":"white","font_size":"fs-6","font_line_height":1.7,"font_weight":"font-weight-normal","text_align_lg":"text-lg-start","mb_lg":"2"} -->
<p class="wp-block-blockstrap-blockstrap-widget-heading mb-2 text-white text-start font-weight-normal fs-6" style="line-height:1.7">"Deadlines met, views enjoyed, HookAndSail's strong Wi-Fi and stylish workspace made remote work a breeze. Now that's a business trip I won't forget!"</p>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"Bob","html_tag":"h6","text_color":"white","font_size":"h4","font_weight":"font-weight-bold","text_align_lg":"text-lg-start","mt_lg":"3","mb_lg":"0"} -->
<h6 class="wp-block-blockstrap-blockstrap-widget-heading mt-3 mb-0 text-white text-start font-weight-bold h4">Bob</h6>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"San Fransisco","html_tag":"p","text_color":"white","font_size":"fs-base","font_weight":"font-weight-normal","text_align_lg":"text-lg-start","mb_lg":"0"} -->
<p class="wp-block-blockstrap-blockstrap-widget-heading mb-0 text-white text-start font-weight-normal fs-base">San Fransisco</p>
<!-- /wp:blockstrap/blockstrap-widget-heading --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container -->